name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 获取代码

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip  # 下载指定版本的 Gradle
        unzip gradle-7.6-bin.zip  # 解压 Gradle
        sudo mv gradle-7.6 /opt/gradle  # 移动到 /opt/gradle 目录
        sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle  # 创建符号链接

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # 设置 Java 版本，确保与您的项目兼容
        distribution: 'zulu'  # 使用 Zulu 提供的 OpenJDK

    - name: Build with Gradle
      run: gradle assembleRelease  # 使用安装的 Gradle 构建 APK

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk  # 上传生成的 APK
        path: app/build/outputs/apk/release/app-release.apk  # APK 的路径
