name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # 使用 Java 11
        distribution: 'zulu'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip  # 下载指定版本的 Gradle
        unzip gradle-7.0.2-bin.zip  # 解压 Gradle
        sudo mv gradle-7.0.2 /opt/gradle  # 移动到 /opt/gradle 目录
        sudo rm -f /usr/bin/gradle  # 删除现有的 gradle 符号链接
        sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle  # 创建新的符号链接

    - name: Build with Gradle (without gradle wrapper)
      run: gradle clean assembleRelease --stacktrace --debug  # 启用调试模式

    - name: List output files
      run: |
        echo "Listing APK files"
        ls -R app/build/outputs/apk/  # 列出生成的 APK 文件，帮助调试路径

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # 确保路径正确
