name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
        unzip gradle-7.6-bin.zip
        sudo mv gradle-7.6 /opt/gradle
        sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle

    - name: Build with Gradle
      run: gradle assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
